BLUETOOTH_ENABLE 		= yes
BLUETOOTH_DRIVER        = iton_bt
LTO_ENABLE              = yes
DEFERRED_EEPROM_SAVE	= yes

DEFERRED_EEPROM_DELAY	= 10000

ifeq ($(strip $(DEFERRED_EEPROM_SAVE)), yes)
    OPT_DEFS += -DDEFERRED_EEPROM_SAVE
    OPT_DEFS += -DEEPROM_FLUSH_DELAY_MS=$(strip $(DEFERRED_EEPROM_DELAY))
endif
